apiVersion: v2
name: nebari-superset
description: A Nebari Software Pack for Apache Superset
type: application
version: 0.4.0
appVersion: "6.1.0"

dependencies:
  - name: superset
    version: "0.17.2"
    repository: "https://apache.github.io/superset"
